credentials:
  usernames:
    dquinn:
      email: dquinn@gmail.com
      name: Daniel Quinn
      password: abc
cookie:
  expiry_days: 0
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - dquinn@gmail.com